debug: none
server_log: false
stats: true
tracker: true
language: en
onlyPVPinArena: false
safeadmin: true
y-offset: 0.5
whitelist:
- ungod
use_shortcuts: false
only_shortcuts: false
consoleoffduty: false
update:
  mode: both
  type: beta
  modules: true
materialprefixes:
- minecraft
- bukkit