debug: none
server_log: false
stats: true
tracker: true
modulecheck: true
language: en
onlyPVPinArena: false
update: both
updatetype: beta
safeadmin: true
y-offset: 0.5
whitelist:
- ungod
use_shortcuts: false
only_shortcuts: false